exchange:
  name: binance
  testnet: true
  credentials:
    api_key_env: BINANCE_API_KEY
    api_secret_env: BINANCE_API_SECRET
  rate_limits:
    orders_per_minute: 50
    requests_per_minute: 1200

trading_pairs:
  - symbol: BTCUSDT
    min_order_size: 0.001
    price_precision: 2
    quantity_precision: 6
  - symbol: ETHUSDT
    min_order_size: 0.01
    price_precision: 2
    quantity_precision: 5

strategies:
  statistical_pattern:
    enabled: true
    parameters:
      lookback_period: 20
      volatility_window: 20
      entry_threshold: 2.0
      exit_threshold: 1.0
      position_size: 0.1
    risk_management:
      max_position_size: 0.5
      stop_loss: 0.02
      take_profit: 0.05

risk_management:
  max_drawdown: 0.1
  max_leverage: 3.0
  position_sizing:
    max_position_pct: 0.2
    risk_per_trade: 0.01
  stop_loss:
    enabled: true
    type: trailing
    initial: 0.02
    trailing_distance: 0.01

monitoring:
  metrics:
    - total_pnl
    - win_rate
    - sharpe_ratio
    - max_drawdown
  logging:
    level: INFO
    file: logs/pythia.log
  alerts:
    enabled: true
    channels:
      - console
      - file
