# Pythia Trading Bot Configuration

# Exchange Configuration
exchange:
  name: "binance"
  testnet: true  # Use testnet for development
  credentials:
    api_key_env: "BINANCE_API_KEY"
    api_secret_env: "BINANCE_API_SECRET"
  rate_limits:
    max_requests_per_minute: 1200
    max_orders_per_second: 10

# Trading Pairs Configuration
trading_pairs:
  - symbol: "BTC/USDT"
    min_order_size: 0.001
    price_precision: 2
    quantity_precision: 6
  - symbol: "ETH/USDT"
    min_order_size: 0.01
    price_precision: 2
    quantity_precision: 5

# Strategy Configuration
strategies:
  statistical_pattern:
    enabled: true
    parameters:
      lookback_period: 252
      regime_threshold: 1.5
      volatility_window: 21
      num_states: 3
      confidence_level: 0.95
    risk_management:
      max_position_size: 0.1  # 10% of portfolio
      stop_loss: 0.02  # 2%
      take_profit: 0.05  # 5%

# Risk Management
risk_management:
  max_portfolio_risk: 0.02  # 2% maximum portfolio risk
  max_drawdown: 0.15  # 15% maximum drawdown
  position_sizing:
    method: "kelly_criterion"
    fraction: 0.5  # Half-Kelly for conservative sizing

# Performance Monitoring
monitoring:
  metrics_update_interval: 60  # seconds
  save_trades: true
  performance_metrics:
    - "sharpe_ratio"
    - "sortino_ratio"
    - "max_drawdown"
    - "win_rate"
    - "profit_factor"

# Database Configuration
database:
  type: "sqlite"  # or postgresql for production
  path: "data/pythia.db"

# Logging Configuration
logging:
  level: "INFO"
  file_path: "logs/pythia.log"
  max_file_size: 10485760  # 10MB
  backup_count: 5
